export {default as customFonts} from '../assets/img/customFonts.jpg'
export {default as freevspro} from '../assets/img/freevspro.webp'
export {default as GDPR} from '../assets/img/GDPR.jpg'
export {default as logo} from '../assets/img/logo.png'
export {default as proLogo} from '../assets/img/pro-logo.png'
export {default as pluginsSetup} from '../assets/img/pluginsSetup.jpg'
export {default as salesFunnel} from '../assets/img/salesFunnel.jpg'
export {default as SEO} from '../assets/img/SEO.jpg'
export {default as themeClub} from '../assets/img/themeClub.jpg'
export {default as themeInstallation} from '../assets/img/themeInstallation.jpg'
export {default as vipSiteCare} from '../assets/img/vipSiteCare.jpg'
export {default as vipSupport} from '../assets/img/vipSupport.jpg'
export {default as mainDemo} from '../assets/img/main-demo.webp'
export {default as demo2} from '../assets/img/demo2.webp'
export {default as demo3} from '../assets/img/demo3.webp'
export {default as demo4} from '../assets/img/demo4.webp'
export {default as demo5} from '../assets/img/demo5.webp'


